const dicCods = {
  "Administração": "ADM",
  "Administração Pública": "CodigoGen0",
  "Administração Pública (EaD)": "D",
  "Arquitetura e Urbanismo": "ARQ",
  "Artes Cênicas (Bacharelado)": "ACB",
  "Artes Cênicas (Licenciatura)": "ACL",
  "Ciência da Computação": "COM",
  "Ciência e Tecnologia de Alimentos": "ALI",
  "Ciências Biológicas (Bacharelado)": "CBB",
  "Ciências Biológicas (Licenciatura)": "CBL",
  "Ciências Econômicas": "ECO",
  "Direito": "DIR",
  "Educação Física (Bacharelado)": "EFB",
  "Educação Física (Licenciatura)": "EFL",
  "Engenharia Ambiental": "AMB",
  "Engenharia Civil": "CIV",
  "Engenharia de Computação": "CJM",
  "Engenharia de Controle e Automação": "AUT",
  "Engenharia de Minas": "MIN",
  "Engenharia de Produção (JM)": "PJM",
  "Engenharia de Produção (OP)": "PRO",
  "Engenharia Elétrica": "EJM",
  "Engenharia Geológica": "GEO",
  "Engenharia Mecânica": "MEC",
  "Engenharia Metalúrgica": "MET",
  "Engenharia Urbana": "URB",
  "Estatística e Ciência de Dados": "EST",
  "Farmácia": "FAR",
  "Filosofia (Bacharelado)": "FLB",
  "Filosofia (Licenciatura)": "FLL",
  "Física (Bacharelado)": "FSB",
  "Física (Licenciatura)": "FSL",
  "Geografia (EaD)": "D",
  "História (Bacharelado)": "HIB",
  "História (Licenciatura)": "HIL",
  "Jornalismo": "JOR",
  "Letras (Bacharelado)": "LTT",
  "Letras (Licenciatura)": "LTE",
  "Matemática (EaD)": "D",
  "Medicina": "MED",
  "Museologia": "MUL",
  "Pedagogia": "PED",
  "Pedagogia (EaD)": "D",
  "Química": "QLI",
  "Química Industrial": "QUI",
  "Serviço Social": "SER",
  "Sistemas de Informação": "SJM"
};